Iterator Helpers are now in stage 3
compat-table/node-compat-table pull request #86
Opened 2023-04-20 05:22 UTC by JamieMagee

https://github.com/tc39/proposal-iterator-helpers/pull/251

2023-04-20 05:32 UTC, ljharb requested changes

2023-04-20 05:32 UTC, ljharb commented on testers.json
> +    "Stage 3›Iterator Helpers›instanceof AsyncIterator": {
async iterator helpers are still stage 2.

2023-04-20 05:32 UTC, ljharb commented on testers.json
> +    "Stage 2›Class and Property Decorators›class decorators": {
decorators are stage 3 now

2023-04-20 05:32 UTC, ljharb commented on testers.json
> +    "Stage 2›Set methods›Set.prototype.symmetricDifference": {
set methods are stage 3 now

2023-04-20 05:32 UTC, ljharb commented on testers.json
> +    "Stage 2›ArrayBuffer.prototype.transfer›ArrayBuffer.prototype.transfer()": {
transfer and transferToFixedLength and .disposed are stage 3 now (realloc is gone)

2023-06-06 03:16 UTC, closed without merging

2023-06-06 03:25 UTC, ljharb commented
@JamieMagee do you no longer have interest in completing this PR?

2023-06-07 16:51 UTC, JamieMagee commented
Sorry, I don't have capacity (or the knowledge) to make the changes.